### ISSUE TITLE
How to encode pose?

### ISSUE THREAD

**Issue by chester256** [aim-uofa/GenPercept#1]
Thank you for the code. How do you encode the 17-channel heatmaps to 3 channels to fit the VAE?

**Comment by YongtaoGe** [comment]
Hi, we encode the heatmaps with predefined colormaps, which is similar to Painter. You can have a reference from [here](https://github.com/baaivision/Painter/blob/7ac5aefe28e711f7daef495bb07aa1605ad4addc/Painter/data/mmpose_custom/data/pipelines/custom_transform.py#L39).
