### ISSUE TITLE
How did you deal with text prompt?

### ISSUE THREAD

**Issue by CoinCheung** [aim-uofa/GenPercept#15]
Hi,

SD2.1 is a text-to-image generation model, which requires a text-prompt as input. In the pretraining stage of SD2.1, they also feed text prompt into the image. If we would like to finetune the pretrainined SD2.1 in downstream tasks such as depth estimation, the downstream dataset does not provide a text-prompt. In this case, did you finetune the SD2.1 model without a text, if so how did you meets the model's requirement of text prompt?

**Comment by guangkaixu** [comment]
We simply set an empty text prompt, i.e., "".  The ablation study in Table 3 shows a small performance change between different text prompts, even a random one.

**Comment by CoinCheung** [comment]
Thanks!!
