### ISSUE TITLE
Specific data amount on hypersim & v-kitti for depth prediction

### ISSUE THREAD

**Issue by haodong2000** [aim-uofa/GenPercept#6]
Dear authors, excellent work, it would be a milestone in CV community!

I got an simple question: what is the specific data amount of hypersim & v-kitti used for training depth estimator.

For instance, in hypersim, did you used only the training split (54K), or the entire dataset (74K)?

Thanks so much!

**Comment by guangkaixu** [comment]
Hi, thanks for being interested in our work! 

For hypersim, we use the training split after filtering some invalid scenes and images. (e.g., depth images with nan value, images with all 255 or 0, and some broken scenes in [this issue of hypersim](https://github.com/apple/ml-hypersim/issues/22]).

For virtual kitti, we use all the image-depth pairs. We set the sky depth value to the maximum depth except the sky area. For example, the sky is 655.35m, and the farthest road is 100m away, and we set the sky depth to 100m. The depth_{sky} value changes for each image.
