### ISSUE TITLE
Huggingface Depth demo gives Error as result

### ISSUE THREAD

**Issue by gituser123456789000** [aim-uofa/GenPercept#7]
The huggingface depth demo appears to not be working. It keeps resulting in "Error", which the other two demo tabs do work.

**Comment by IcelandicCenterArtificialIntelligence** [comment]
Same. However in our case all demos are failing.

**Comment by guangkaixu** [comment]
@gituser123456789000 @IcelandicCenterArtificialIntelligence Hi, we have updated GenPercept v2 and fixed the bug of huggingface.
