### ISSUE TITLE
Local Installation Explanation

### ISSUE THREAD

**Issue by gituser123456789000** [aim-uofa/GenPercept#8]
Some additional local installation tips would be appreciated. I can't get your project running.

It seems this checkpoint is needed:
https://pan.baidu.com/s/1n6FlqrOTZqHX-F6OhcvNyA?pwd=g2cm

But the website is in Chinese and it requires a separate application download? And you have to make an account within this app?

You have huggingface and another option to download the model, but I don't see the 9.14GB genpercept_ckpt_v1 file on huggingface.

The third option "or [Rec Cloud Disk (To be uploaded)](https://github.com/aim-uofa/GenPercept/blob/main)" just links to the github project page, not to a checkpoint ckpt file.

**Comment by gituser123456789000** [comment]
Or show what the folder structure is supposed to look like..

I have this in GenPercept > weights > v1
<img width="766" alt="folderstructure" src="https://github.com/user-attachments/assets/22cc564e-cb83-4e1e-a4b4-049b3cb848ee">

**Comment by gituser123456789000** [comment]
I got it running.. Chinese site was not needed

After everything is setup correctly.. like I showed in the picture 

go back to the main GenPercept folder.. right-click in the empty space and Open Git Bash here

then you run
sh scripts/inference_depth.sh

and it will start running.. and producing depth maps from what you have in the input > depth folder.. and will output to output > depth > depth_colored

It will output colored maps, which are unusable in most or all conversion programs..

so you need to go into GenPercept > tools folder and open the inference_genpercept.py file in an editor like Notepad++ and edit line 132 to say:
default="binary",

this will make white front / black rear color maps instead of colored maps

**Comment by guangkaixu** [comment]
Thanks so much for your correction! The old code has been moved to "GenPercept_v1", and we have released the latest code corresponding to the (arxiv v3 paper)[https://arxiv.org/abs/2403.06090]. Welcome to give it a try!
